[plugin]          
internal_name = "SillyLizard"          
display_name = "SillyLizard"          
author = "Oak"          
description = "Silly Lizards go here!"          
punchline = "Hey there."          
repo_url = "https://github.com/WondrousAJ/silly-lizard"          
tags = ["Lizards"]          
icon_url = "https://tykku.github.io/ToshiBox/release/images/icon.png"          
assembly_version = "7.4.5.1"          
dalamud_api_level = 12          
download_link_install = "https://WondrousAJ.github.io/silly-lizard/release/SillyLizard.zip"          
changelog = "Auto-published version 7.4.5.1"      
